In [1]:
import pandas as pd

df = pd.DataFrame({'name' : ['김지훈', '이유진', '박동현', '김민지'],
                   'english' : [90, 80, 60, 70],
                   'math' : [50, 60, 100, 20]})
df

  name  english  math
0  김지훈       90    50
1  이유진       80    60
2  박동현       60   100
3  김민지       70    20

In [3]:
df['english']

0    90
1    80
2    60
3    70
Name: english, dtype: int64

In [4]:
sum(df['english'])

300

In [5]:
sum(df['math'])

230

In [6]:
sum(df['english'])/4

75.0

In [8]:
df = pd.DataFrame({'제품' : ['사과', '딸기', '수박'],
                   '가격' : [1800, 1500, 3000],
                   '판매량' : [24, 38, 13]})
df

   제품    가격  판매량
0  사과  1800   24
1  딸기  1500   38
2  수박  3000   13

In [9]:
sum(df['가격'])/3

2100.0

In [10]:
sum(df['판매량'])/3

25.0

In [15]:
df_exam = pd.read_excel('data/excel_exam.xlsx')
df_exam

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
2    3       1    45       86       78
3    4       1    30       98       58
4    5       2    25       80       65
5    6       2    50       89       98
6    7       2    80       90       45
7    8       2    90       78       25
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32
12  13       4    46       98       65
13  14       4    48       87       12
14  15       4    75       56       78
15  16       4    58       98       65
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [16]:
sum(df_exam['math'])/20

57.45

In [17]:
sum(df_exam['math'])/len(df_exam)

57.45

In [18]:
len(df_exam)

20

In [20]:
df_exam_novar = pd.read_excel('data/excel_exam_novar.xlsx')
df_exam_novar

   1  1.1  50  98  50.1
0  2    1  60  97    60
1  3    2  25  80    65
2  4    2  50  89    98
3  5    3  20  98    15
4  6    3  50  98    45
5  7    4  46  98    65
6  8    4  48  87    12

In [21]:
df_exam_novar = pd.read_excel('data/excel_exam_novar.xlsx', header = None)
df_exam_novar

   0  1   2   3   4
0  1  1  50  98  50
1  2  1  60  97  60
2  3  2  25  80  65
3  4  2  50  89  98
4  5  3  20  98  15
5  6  3  50  98  45
6  7  4  46  98  65
7  8  4  48  87  12

In [25]:
df_csv_exam = pd.read_csv('data/exam.csv')
df_csv_exam

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
2    3       1    45       86       78
3    4       1    30       98       58
4    5       2    25       80       65
5    6       2    50       89       98
6    7       2    80       90       45
7    8       2    90       78       25
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32
12  13       4    46       98       65
13  14       4    48       87       12
14  15       4    75       56       78
15  16       4    58       98       65
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [29]:
sales = pd.DataFrame({'제품' : ['사과', '딸기', '수박'],
                   '가격' : [1800, 1500, 3000],
                   '판매량' : [24, 38, 13]})
sales

   제품    가격  판매량
0  사과  1800   24
1  딸기  1500   38
2  수박  3000   13

In [31]:
sales = pd.DataFrame({'제품' : ['사과', '딸기', '수박'],
                   '가격' : [1800, 1500, 3000],
                   '판매량' : [24, 38, 13]})
sales
sales.to_csv('data/out_sales.csv', encoding = 'cp949')

In [32]:
sales.to_csv('data/out_sales_1.csv', encoding = 'cp949', index = False)

In [33]:
df_exam

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
2    3       1    45       86       78
3    4       1    30       98       58
4    5       2    25       80       65
5    6       2    50       89       98
6    7       2    80       90       45
7    8       2    90       78       25
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32
12  13       4    46       98       65
13  14       4    48       87       12
14  15       4    75       56       78
15  16       4    58       98       65
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [34]:
df_exam.head()

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60
2   3       1    45       86       78
3   4       1    30       98       58
4   5       2    25       80       65

In [35]:
df_exam.head(10)

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60
2   3       1    45       86       78
3   4       1    30       98       58
4   5       2    25       80       65
5   6       2    50       89       98
6   7       2    80       90       45
7   8       2    90       78       25
8   9       3    20       98       15
9  10       3    50       98       45

In [36]:
df_exam.tail(5)

    id  nclass  math  english  science
15  16       4    58       98       65
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [37]:
df_exam.tail(10)

    id  nclass  math  english  science
10  11       3    65       65       65
11  12       3    45       85       32
12  13       4    46       98       65
13  14       4    48       87       12
14  15       4    75       56       78
15  16       4    58       98       65
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [39]:
df_exam.shape

(20, 5)

In [40]:
df_exam.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       20 non-null     int64
 1   nclass   20 non-null     int64
 2   math     20 non-null     int64
 3   english  20 non-null     int64
 4   science  20 non-null     int64
dtypes: int64(5)
memory usage: 932.0 bytes

In [41]:
df_exam.describe()

             id     nclass       math    english    science
count  20.00000  20.000000  20.000000  20.000000  20.000000
mean   10.50000   3.000000  57.450000  84.900000  59.450000
std     5.91608   1.450953  20.299015  12.875517  25.292968
min     1.00000   1.000000  20.000000  56.000000  12.000000
25%     5.75000   2.000000  45.750000  78.000000  45.000000
50%    10.50000   3.000000  54.000000  86.500000  62.500000
75%    15.25000   4.000000  75.750000  98.000000  78.000000
max    20.00000   5.000000  90.000000  98.000000  98.000000