In [2]:
import pandas as pd
print(pd.__version__)

3.0.3

In [4]:
fruits = ["apple", "banana", "cherry", "durian"]
series_str = pd.Series(fruits)

In [5]:
print(series_str)

0     apple
1    banana
2    cherry
3    durian
dtype: str

In [6]:
exam = pd.read_csv('data/exam.csv')

In [8]:
exam.head()

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60
2   3       1    45       86       78
3   4       1    30       98       58
4   5       2    25       80       65

In [9]:
exam.head(3)

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60
2   3       1    45       86       78

In [ ]:
exam.head()